set registry

diff --git a/.github/workflows/main_cd.yaml b/.github/workflows/main_cd.yaml
--- a/.github/workflows/main_cd.yaml
+++ b/.github/workflows/main_cd.yaml
@@ -87,6 +87,17 @@ jobs:
         run: |
           poetry run dvc pull && echo "Data successfully pulled from DVC" || echo "No data found in DVC"
 
+      - name: Log in to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Validate Environment Variables
+        run: |
+          if [[ -z "${{ steps.login-ecr.outputs.registry }}" ]]; then
+            echo "Error: REGISTRY is not set!"
+            exit 1
+          fi
+
       - name: Create .env file
         run: |
           echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
